# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cSnWiDnClyIOq-iA243beTSbJkF_sF4E
"""

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Sample dataset
movies = pd.DataFrame({
    'title': ['Inception', 'Interstellar', 'The Dark Knight', 'Memento', 'The Prestige', 'Shutter Island'],
    'tags': ['dream heist sci-fi', 'space sci-fi epic', 'hero vigilante action', 'memory mystery thriller', 'magic mystery drama', 'psychological thriller mystery']
})

# Convert 'tags' to feature vectors
cv = CountVectorizer(stop_words='english')
vectorized_matrix = cv.fit_transform(movies['tags'])

# Compute cosine similarity
similarity = cosine_similarity(vectorized_matrix)

# Recommendation function
def recommend(movie):
    try:
        movie_index = movies[movies['title'] == movie].index[0]  # Get the index of the movie
        distances = similarity[movie_index]  # Get similarity scores
        movie_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]  # Top 5 similar movies

        # Print movie recommendations
        print(f"Movies similar to '{movie}':")
        for i in movie_list:
            print(movies.iloc[i[0]].title)
    except IndexError:
        print(f"'{movie}' not found in the dataset. Please try a different title.")

# Example usage
recommend('Inception')